-- Generated by GmodSoundGen

-- File: D:\Downloads\important_stuff_v2\Tools\GmodSoundGen_0519\v2\weapon_sm_mpapa5.all.lua
-- Total length: 85

-- Sound: 0
sound.Add({
	name = "weap_ar_trlongburst_fire",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = {
		"^weapon_t9/tr_longburst/weap_tr_longburst_start_04a.wav",
		}
})
-- Sound: 0
sound.Add({
	name = "weap_ar_trlongburst_ads_down",
	channel = CHAN_WPNFOLEY + 1,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike4/wfoly_ar_mike4_ads_down.ogg",
		}
})
-- Sound: 1
sound.Add({
	name = "weap_ar_trlongburst_ads_up",
	channel = CHAN_WPNFOLEY + 2,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_mike4/wfoly_ar_mike4_ads_up.ogg",
		}
})
-- Sound: 2
sound.Add({
	name = "wfoly_plr_longburst_empty_end",
	channel = CHAN_WPNFOLEY + 3,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/t9_tr_longburst/fly_tr_longburst_empty_end.ogg",
		}
})
-- Sound: 3
sound.Add({
	name = "wfoly_plr_longburst_fast_bolt_release",
	channel = CHAN_WPNFOLEY + 4,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/t9_tr_longburst/fly_tr_longburst_fast_bolt_release_01.ogg",
		"reloads/t9_tr_longburst/fly_tr_longburst_fast_bolt_release_02.ogg",
		}
})

-- Sound: 16
sound.Add({
	name = "wfoly_plr_longburst_charge_release",
	channel = CHAN_WPNFOLEY + 7,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/t9_tr_longburst/fly_tr_longburst_inspect_pt4.ogg",
		}
})
-- Sound: 17
sound.Add({
	name = "wfoly_plr_longburst_charge_back",
	channel = CHAN_WPNFOLEY + 1,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/t9_tr_longburst/fly_tr_longburst_inspect_pt3.ogg",
		}
})
-- Sound: 4
sound.Add({
	name = "wfoly_plr_longburst_fast_end",
	channel = CHAN_WPNFOLEY + 2,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/t9_tr_longburst/fly_tr_longburst_fast_end.ogg",
		}
})
-- Sound: 5
sound.Add({
	name = "wfoly_plr_longburst_fast_mag_in",
	channel = CHAN_WPNFOLEY + 6,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/t9_tr_longburst/fly_tr_longburst_fast_mag_in.ogg",
		}
})
-- Sound: 6
sound.Add({
	name = "wfoly_plr_longburst_fast_mag_in_flip",
	channel = CHAN_WPNFOLEY + 7,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/t9_tr_longburst/fly_tr_longburst_fast_mag_in_flip.ogg",
		}
})
-- Sound: 7
sound.Add({
	name = "wfoly_plr_longburst_fast_mag_out",
	channel = CHAN_WPNFOLEY + 8,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/t9_tr_longburst/fly_tr_longburst_fast_mag_out.ogg",
		}
})
-- Sound: 8
sound.Add({
	name = "wfoly_plr_longburst_fast_mag_out_flip",
	channel = CHAN_WPNFOLEY + 9,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/t9_tr_longburst/fly_tr_longburst_fast_mag_out_flip.ogg",
		}
})
-- Sound: 9
sound.Add({
	name = "wfoly_plr_longburst_mag_in",
	channel = CHAN_WPNFOLEY + 10,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/t9_tr_longburst/fly_tr_longburst_mag_in.ogg",
		}
})
-- Sound: 10
sound.Add({
	name = "wfoly_plr_longburst_mag_out",
	channel = CHAN_WPNFOLEY + 1,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/t9_tr_longburst/fly_tr_longburst_mag_out.ogg",
		}
})
-- Sound: 11
sound.Add({
	name = "wfoly_plr_longburst_rattle",
	channel = CHAN_WPNFOLEY + 2,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/t9_tr_longburst/fly_tr_longburst_rattle_01.ogg",
		"reloads/t9_tr_longburst/fly_tr_longburst_rattle_02.ogg",
		"reloads/t9_tr_longburst/fly_tr_longburst_rattle_03.ogg",
		}
})
-- Sound: 12
sound.Add({
	name = "wfoly_plr_longburst_start",
	channel = CHAN_WPNFOLEY + 3,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/t9_tr_longburst/fly_tr_longburst_start.ogg",
		}
})
-- Sound: 13
sound.Add({
	name = "wfoly_plr_longburst_tac_end",
	channel = CHAN_WPNFOLEY + 4,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/t9_tr_longburst/fly_tr_longburst_tac_end.ogg",
		}
})
-- Sound: 14
sound.Add({
	name = "wfoly_plr_trlongburst_inspect_pt1",
	channel = CHAN_WPNFOLEY + 5,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/t9_tr_longburst/fly_tr_longburst_inspect_pt1.ogg",
		}
})
-- Sound: 15
sound.Add({
	name = "wfoly_plr_trlongburst_inspect_pt2",
	channel = CHAN_WPNFOLEY + 6,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/t9_tr_longburst/fly_tr_longburst_inspect_pt2.ogg",
		}
})
-- Sound: 16
sound.Add({
	name = "wfoly_plr_trlongburst_inspect_pt3",
	channel = CHAN_WPNFOLEY + 7,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/t9_tr_longburst/fly_tr_longburst_inspect_pt3.ogg",
		}
})
-- Sound: 17
sound.Add({
	name = "wfoly_plr_trlongburst_inspect_pt4",
	channel = CHAN_WPNFOLEY + 8,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/t9_tr_longburst/fly_tr_longburst_inspect_pt4.ogg",
		}
})
-- Sound: 18
sound.Add({
	name = "wfoly_plr_trlongburst_lower",
	channel = CHAN_WPNFOLEY + 9,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/t9_tr_longburst/fly_tr_longburst_lower.ogg",
		}
})
-- Sound: 19
sound.Add({
	name = "wfoly_plr_trlongburst_raise",
	channel = CHAN_WPNFOLEY + 10,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/t9_tr_longburst/fly_tr_longburst_raise.ogg",
		}
})